### ISSUE TITLE
Thing tile persistance

### ISSUE THREAD

**Issue by burdettadam** [Picolab/Manifold#10]
Find some way to persistently save the information as to where the tiles are located. When a user moves a tile's location somewhere else, they shouldn't have to do it again when they reload the website.

This could be stored in pds ruleset or an ent in manifold.

**Comment by AngelSassin** [comment]
The Manifold SPA now dispatches to the Manifold Pico, sending position information of every thing tile that changed per drag or resize. The Manifold pico stores this information in a map, keyed by the thing names. On page load, this data is sent to the SPA.

Changes are shown in this commit: https://github.com/Picolab/Manifold/commit/7832c383c813b2373ed0175e23d9458b7a95a8e8

**Comment by windley** [comment]
Yay!!

**Comment by AngelSassin** [comment]
Current bug: While making changes to the layout of the Things page saves positions in the Manifold Pico, switching to an alternate page in the sidebar, such as Communities, and back to Things will revert any changes made if the page is not refreshed or reloaded. 

The mapStateToProps function uses the initial state obtained at page load to fill in the grid any time the Things page is opened, such as when switching to Communities to Things. A change should be made such that the data is removed after initial load, or updated to the page state.

**Comment by cgrimm013** [comment]
I am experiencing two bugs right now. 1) When deleting a pico, that pico's position data isn't cleared from the entity variable in the manifold pico. 2) On an initial creation, I get the whole "cannot read property of x" error. If I refresh, it works fine. I think the second error is because Manifold queries for the manifold info before the rule is selected in the manifold pico to set the position values.

**Comment by AngelSassin** [comment]
Deleting a Thing from the Manifold SPA with the `manifold/remove_thing` event will clear the position data from the Manifold pico. Errors in which the positions of the Things cannot be read are now dealt with by giving default values to the Thing tiles. 

Note that the Github version of the manifold_pico.krl ruleset was updated. I have not run into an error with Thing creation and the "cannot read property x of undefined" error.
