### ISSUE TITLE
Manifold Landing Page

### ISSUE THREAD

**Issue by LewisThomas** [Picolab/Manifold#101]
In a meeting we spoke about some sort of Manifold landing page explaining what it is and why for the case of New Student Orientation students might want to bother using it. If they navigate to `manifold.byu.edu` or `manifold.picolabs.io`, there needs to be some professional looking page introducing Manifold and why someone or some student might want to use it.

**Comment by cgrimm013** [comment]
Sign in with google lives here

**Comment by cgrimm013** [comment]
We should include information on how people can get more tags.

**Comment by cgrimm013** [comment]
We just need a picture of the team together!

**Comment by cgrimm013** [comment]
Complete. Just waiting on people's personal bios.
