### ISSUE TITLE
Precise definition of "Community" and its use

### ISSUE THREAD

**Issue by burdettadam** [Picolab/Manifold#11]
Define a community, its use and consider setting up an example community to build and use as a sort of template for Manifold.

**Comment by burdettadam** [comment]
I think a community is just a router Pico with subscriptions to other picos. community rulesets will define the interaction of all the picos with in a community, by using said subscriptions.

**Comment by cgrimm013** [comment]
I'm trying to set up some sort of diagram for the use of communities and the difference between a community and a collection. Check out this link for the diagram and let me know if the link breaks for some reason... https://www.lucidchart.com/documents/view/0234efd9-bfc7-4fe6-9ad0-da85c641d6f5

**Comment by burdettadam** [comment]
I believe a collection is what ROS calls topics. http://wiki.ros.org/Topics

**Comment by windley** [comment]
I think topics are slightly different. Typically a bus isn't programmable. Whereas collections, being built on picos, could act like a simple bus (just route messages) or could do other things. See the [Reactive Pico Patterns](http://www.windley.com/archives/2016/04/reactive_programming_patterns_examples_from_fuse.shtml) for some patterns on this. 

@cgrimm013 I don't think there's a significant architectural distinction between collections and communities at this point. In my head, I think of communities being more "social" but they'll be built on top of a collection.

**Comment by cgrimm013** [comment]
I'm going to close this since we've discussed a good amount about what a community is. I believe its concept will develop more as we produce various apps that would make sense to use them.
