### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#113]
We need some plan for Manifold's future so people are interested.

**Comment by LewisThomas** [comment]
In the meeting on 8/20 we discussed needing answers for some questions, for example, someone CS minded might ask us "How did you build Manifold/Safe And Mine?".

We also want to be able to answer the question "How do I build an app for this?". We need to move towards providing instructions if anyone else wants to build apps for Manifold.

**Comment by cgrimm013** [comment]
No longer relevant
