### ISSUE TITLE
Point domains at the correct locations

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#118]

**Comment by cgrimm013** [comment]
I've set up nginx as a reverse proxy for port 3001 on the apps server. I am waiting for the domain name to point to this ip address so that I can set up SSL with that domain name. I still need to set up nginx for the manifold server.

**Comment by cgrimm013** [comment]
I need to remember to add the nginx config files to the project repository.

**Comment by cgrimm013** [comment]
I set up SSL for apps.picolabs.io. The certificate expires november 5th this year.

**Comment by cgrimm013** [comment]
This is blocked because the domain still points at the github ip address. I can't successfully create an SSL certificate because it keeps challenging the wrong ip address.

**Comment by windley** [comment]
I think I found the problem. Give it some time to propagate and try again.

**Comment by cgrimm013** [comment]
We just got both Manifold and the pico-engine secured with HTTPS.

**Comment by cgrimm013** [comment]
![uploads/68fdfc5e-8a52-43cc-91b7-8f854f6417db/Screen Shot 2018-08-09 at 1.17.37 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F68fdfc5e-8a52-43cc-91b7-8f854f6417db%2FScreen+Shot+2018-08-09+at+1.17.37+PM.png)

**Comment by cgrimm013** [comment]
All the domains point at the right places.
