### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#119]
Authenticating with google provides information like email address and name. It would be cool to autofill their owner pico's profile information with the google provided stuff.

**Comment by LewisThomas** [comment]
A profile ruleset exists on each owner pico, and it should be extendable to hold identifiable information from services other than google. Every time a user signs in with google, their profile information on their owner pico is updated. Attached is the current profile page, any suggestions on it would be appreciated. If not, I'll close this issue as well.


![uploads/47cc67af-3d09-46c2-9a9e-db36ca27e2bf/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F47cc67af-3d09-46c2-9a9e-db36ca27e2bf%2Fimage.png)
