### ISSUE TITLE
Landing page formatting looks odd on some devices

### ISSUE THREAD

**Issue by LewisThomas** [Picolab/Manifold#134]
Pulled up the landing page on my Pixel 2 XL and the formatting for the landing page looks funky and weird. This is in contradiction from when I view the page on chromes version of my phone, which shows it correctly. Picture attached to show what it looks like on my actual phone.

![uploads/d1c8766f-7072-4fac-95e6-f973e53e1409/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd1c8766f-7072-4fac-95e6-f973e53e1409%2Fimage.png)

Maybe we need to test on more devices and fix the landing page.

**Comment by LewisThomas** [comment]
Nvm, I think Jace already fixed this, will make sure this is fixed with him next time he's able to update the production Manifold.

**Comment by KandareJ** [comment]
Ya sorry I fixed that. I didn't make an issue, but it's been to committed to master.
