### ISSUE TITLE
Safe & Mine message box showing 0/250 now

### ISSUE THREAD

**Issue by b1conrad** [Picolab/Manifold#143]
but worked during the session in which I entered text into it.

![screen shot 2018-09-26 at 2 27 30 pm](https://user-images.githubusercontent.com/19273926/46107344-57618a00-c198-11e8-8f5b-145cc5348e4f.png)

**Comment by KandareJ** [comment]
Fixed it to update the message length when the page first loads instead of waiting for the text area to be selected
