### ISSUE TITLE
Monitor Manifold somehow

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#145]
We need a way to monitor Manifold so we don't have to manually check all the time. Maybe this just reports to a slack channel once a day or something and tells us immediately if something breaks...

**Comment by cgrimm013** [comment]
I have a simple solution for this. I wrote a short file called monitor.js which lists all the processes currently running using the forever module. Then I check specifically for Manifold and the pico-engine. If they are not running, then I post a webhook to the Manifold Slack channel reporting which processes are not currently down. I use node-cron to continuously reexecute this check every x amount of time. I haven't determined the amount of time yet, but I have the slack webhook working. 

This method relies on Amazon to report when the instance itself goes down. I'm trying to avoid spamming the slack channel with "Manifold is OK" type messages, so I only send a message when there is a problem.

I still need to do some more testing just to confirm that it works correctly, which may put Manifold/the pico-engine down for a little. I'll work on that tomorrow.

**Comment by windley** [comment]
Good. I like it. Let’s review in lab meeting.

**Comment by cgrimm013** [comment]
I went ahead and did a little testing and started the script with forever. One thing that the script will not detect is if the engine or manifold is still running, but has become unresponsive for some reason. e.g. two picos are deadlocked because they queried each other.
