### ISSUE TITLE
Reminder app

### ISSUE THREAD

**Issue by KandareJ** [Picolab/Manifold#167]

**Comment by KandareJ** [comment]
The reminder app would let you set reminders for yourself at certain times. Manifold would then send you a notification when that time comes.

**Comment by b1conrad** [comment]
Got a request at UAPI for something similar. The idea is the app has a registered QR Code tag. When you scan it, the app records that and sets a timer for a reminder to the owner to do the same thing again and scan the tag again. Real world example: changing a furnace filter. Your furnace thing would have this app installed, and the registered QR Code would be placed in a conspicuous location on the furnace
