### ISSUE TITLE
Could Manifold SPA display an error message from pico-engine

### ISSUE THREAD

**Issue by b1conrad** [Picolab/Manifold#168]
When the pico-engine cannot provide an Owner pico for some reason, an error of some kind is provided instead. It would be nice if that error were displayed to the owner in the Manifold screen.

Phil suggests, "There should be a standard error display routine that consistently shows errors, warnings, etc to users." [from slack]

**Comment by nmartinezbyu** [comment]
I have created a modal that uses redux in order to know when to display and what to display. It also lets you copy the error message so that a manifold user can send it to us if they ever encounter an error. I am currently working on further testing.

**Comment by nmartinezbyu** [comment]
I have made the pull request that will add the new error message modal to master.
