### ISSUE TITLE
polling is taking a toll

### ISSUE THREAD

**Issue by b1conrad** [Picolab/Manifold#177]
Manifold the SPA does polling for various reasons. But the motivation is to have the UI updated when things happen in outside systems. Ideally such systems could send an event to the browser (but we don't (yet) have web sockets).

Can we stop the polling when the tab containing Manifold loses focus? Then resume when focus returns? This would stop the polling when it isn't needed while maintaining the desired UX.

**Comment by b1conrad** [comment]
exponential back off? see [TicTacToe repo](https://github.com/Picolab/TicTacToe/blob/master/krl/org.sovrin.tic_tac_toe.ui.krl#L109-L137)

**Comment by nmartinezbyu** [comment]
Currently working on exponential backoff. I have been looking at the TicTacToe repo for guidance.

**Comment by nmartinezbyu** [comment]
Exponential back off working on manifold notifications, now I just need to implement it on the manifold aca agent app so basic messaging is using exponential back off as well.

**Comment by nmartinezbyu** [comment]
I forgot to mention that these changes have only been done on the ACA-Agent-UI branch and have not been pushed to master.

**Comment by nmartinezbyu** [comment]
Exponential back off has been implemented on the aca agent app.

**Comment by nmartinezbyu** [comment]
I have added the pull request that will add polling for notifications and polling for the manifold aries cloud agent app.
