### ISSUE TITLE
Manifold incorrectly installs

### ISSUE THREAD

**Issue by AngelSassin** [Picolab/Manifold#21]
When I installed Manifold on my machine (Macbook running Windows 8.1 OS with bootcamp), the installation didn't completely run correctly. I tried several times, and the error was the same. 

```
Failed to compile

./~/react-dom/lib/ReactMount.js

Module not found: Can't resolve 'react/lib/React' in 'C:\Users\nikk29\Documents\GitHub\Manifold\node_modules\react-dom\lib'
```

The issue turned out to be that the react module was installing in a separate folder. Instead of installing `react.js` and the `/lib` folder under `node_modules/react`, they were being installed in `node_modules\react-google-charts\node_modules\react` instead. I fixed the issue by copy/pasting the react folder in the google charts directory into my root node_modules directory.

I'm not sure why the installation occurs this way on my machine and correctly on others' machines.

**Comment by cgrimm013** [comment]
I had this same error when trying to do a fresh install of Manifold just recently. I tracked it down to some outdated dependencies and updated them in our repository. Hopefully everything will work, but I'd be curious to see what other people encounter when they try installing on different machines.

**Comment by burdettadam** [comment]
I got a different error with node@10, but everything work with node@8. I think this issue is resolved.
