### ISSUE TITLE
Manifold Website tests

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#22]
I have no idea how testing a website works. Research more into this and begin writing standard test cases to prevent regressions in our code.

**Comment by cgrimm013** [comment]
I found some information on writing tests in the Create React App README.md. I'm going to try to figure that out and write a documentation page about how to write tests.

**Comment by cgrimm013** [comment]
I created the initial documentation page for how to write tests for Manifold and created an example test in the project structure. Next step: write tests for the components we've been creating and add more documentation on the different kinds of tests we make.

**Comment by windley** [comment]
You can do a lot with good tests of the react components. You use a tool like Selenium (although I don't know if that's still the best) to test the actual site. The react component testing can do 90% of the job.

**Comment by cgrimm013** [comment]
Hmm, I'll look into that. That definitely seems like a worthy pursuit.

**Comment by cgrimm013** [comment]
To better keep track of tests, I'm going to open some new issues about specific tests I'm trying to create rather than logging everything here. I'll move this to review for now.

**Comment by cgrimm013** [comment]
I'm moving this back into working. This issue can be used to keep track of which aspects of our project we are working on testing. 
My ideas for what we can add tests for:
1) All of our components
2) Redux actions (this includes the Oauth action)
3) Redux-saga functions
4) Redux reducers

Currently everything just follows the happy path. If we continue developing without writing tests for all the above things, we will run into far more problems than we otherwise would. Also, this will not only help with regression testing, but to finally add error handling in our code. This will greatly help debugging when we can bunker down and develop Manifold more.

**Comment by cgrimm013** [comment]
This will help with issue #17

**Comment by cgrimm013** [comment]
We don't need an issue for this anymore
