### ISSUE TITLE
How should rulesets work on an individual device?

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#27]
Currently, there are two rulesets needed for a wovyn device. The wovyn_router, which takes in temperature readings and saves the most recent/determines whether it was a temperature or a humidity reading etc. Then there is also the wovyn_device.krl ruleset which listens in on any new_temperature_reading and only acts if there is a threshold violation. 

I would rather have this structured so that the pico remembers a set number of readings, rather than just the last one seen. Let's say that one wovyn device reports multiple things, like temperature and also humidity. It would be nice in Manifold to see both the temperature report as its own app, and also maybe the humidity report on the same thing tile.

**Comment by windley** [comment]
Are you counting these? There's more than two here and some are more general, if I remember. Not all have been ported to NPE.

**Comment by cgrimm013** [comment]
These? What are you referring to? I am just referring to the rulesets we used in the last closet demo at open west.

**Comment by windley** [comment]
Sorry. https://github.com/Picolab/Wovyn/tree/master/krl

**Comment by cgrimm013** [comment]
This issue is not currently relevant, and is an enhancement on the Wovyn ruleset, not Manifold
