### ISSUE TITLE
Remove all warnings

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#31]
dozens of warnings show up when running npm start. I want to clear them all up so we can see warnings in real time as we develop.

**Comment by cgrimm013** [comment]
Fixed them! Instead of seeing dozens of warnings, we see:

![uploads/30cbb272-db1c-41cf-abde-42958260da76/Screen Shot 2018-04-27 at 3.32.20 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F30cbb272-db1c-41cf-abde-42958260da76%2FScreen+Shot+2018-04-27+at+3.32.20+PM.png)

**Comment by cgrimm013** [comment]
Now when we do something dumb, it should spit yellow texted poison at us. :)

**Comment by windley** [comment]
Nice!
