### ISSUE TITLE
Remove the hashtag from url

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#32]
A hashtag currently sits in our url whenever we are navigating around. This works fine for development, but from what I understand, it is not a production ready thing, and it affects our use of oauth, so I'd prefer it to be removed.

**Comment by cgrimm013** [comment]
Also, I'll try to update the using manifold docs so the # isn't included in the Oauth redirect.

**Comment by windley** [comment]
The hashtag in the URL is called a fragment and it's normal in single page applications.

**Comment by cgrimm013** [comment]
Ok. So is the # something we want in our URL's? If I try navigating to localhost:3000/mythings, the router redirects it to localhost:3000/mythings#/mythings, and after that keeps the beginning "mythings" no matter where I redirect to. I haven't looked into how to fix that yet besides removing the # altogether.

**Comment by windley** [comment]
I don’t know why it has the double name. That’s probably something we’d like to fix. But having the current page state of the SPA in the fragment is how the SPA keeps track of where it is.

**Comment by cgrimm013** [comment]
Ok, so unless we come across a situation where we need to do something differently, I'll leave it be.
