### ISSUE TITLE
Sass compiling

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#33]
Currently, modifying a .scss file does not automatically compile the scss into a new style.css file in the public folder. In other words, changes to a .scss file will never display on the Manifold website. It would be nice to have some documentation on how to compile this, or perhaps we can find a way to autocompile changes as they are made by including another script during npm start that watches for changes in the .scss files.

**Comment by cgrimm013** [comment]
I figured out what was going on with this and wrote up a documentation page about how to properly add styling in Manifold. Here is the page link: https://picolabs.atlassian.net/wiki/spaces/docs/pages/363298817/Adding+Custom+Styles+CSS+and+Sass#AddingCustomStyles(CSSandSass)-UsingSass

**Comment by windley** [comment]
Good!
