### ISSUE TITLE
Manifold Developers Introduction Page

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#37]
Make a page that new hires can read and refer to in order to get jumpstarted on Manifold without being completely lost.

**Comment by cgrimm013** [comment]
Initial draft has been written. Looking for some more reviews.

**Comment by windley** [comment]
Link?

**Comment by cgrimm013** [comment]
https://picolabs.atlassian.net/wiki/spaces/docs/pages/363364396/Developer+s+Introduction I just posted it in the Manifold slack channel too.
