### ISSUE TITLE
Deployment script

### ISSUE THREAD

**Issue by burdettadam** [Picolab/Manifold#44]
We need a script to deploy changes to manifold production.
The script should work something like:
  - run all test on master branch, exiting on failed test.
  - pull changes from master to a staging branch for gh-pages, ignoring configuration files (production 
    configuration will be different).
  - run webpack build command.
  - pull built manifold to gh-pages for github to serve.

**Comment by burdettadam** [comment]
This issue requires a solution for https://github.com/Picolab/Manifold/issues/40. This directly affects the production configuration files.

**Comment by cgrimm013** [comment]
There is probably some tool or guide out there for automatically deploying a react project from a github repo to an ec2 instance.

**Comment by cgrimm013** [comment]
I think documentation is automation in this case. Jace knows the steps
