### ISSUE TITLE
Fix btn warning

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#60]
The following warning appears when rendering footer items:

![uploads/55b413d9-1ce9-4e05-a9f1-8e3b5e242d5a/Screen Shot 2018-05-08 at 2.50.06 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F55b413d9-1ce9-4e05-a9f1-8e3b5e242d5a%2FScreen+Shot+2018-05-08+at+2.50.06+PM.png)

Figure out what's up with that.

**Comment by KandareJ** [comment]
just switched it to a <div> and it seems to be working fine
