### ISSUE TITLE
Small view

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/Manifold#77]
The card body is quite small, and any overflow is impossible to view without explicitly making the card a ton bigger. I wonder if we can add a scrollable little window in the thing body. Of course, we still need to create a bigger page just for that thing so we can do bigger and better things.

**Comment by windley** [comment]
What about a less/more toggle that expands the card. Just the first part otherwise.

**Comment by cgrimm013** [comment]
Possibly. I'd have to research how to expand until there is no more overflow.

**Comment by cgrimm013** [comment]
Just for easy servicing, I added the overflow to be scrollable.

**Comment by cgrimm013** [comment]
#89 will help with this. The question still remains however... should we allow the card to be expandable, or limit the size and require people to go into the app page for the thing if they want to see more?

**Comment by KandareJ** [comment]
We added in a separate page for each app on a card.
